import csv, io, re, unicodedata, json

# 1,128 ترجمة مستخرجة من translated_players.txt
FILL = json.loads(r"""{
"Saeed Baattia": "سعيد باطيّة",
"Eid Al Muwallad": "عيد المولد",
"Pedro Rebocho": "بيدرو ريبوتشو",
"Abdulelah Al Khaibari": "عبدالإله الخيبري",
"Mailson": "مايلسون",
"Abdulquddus Atiah": "عبدالقدوس عطية",
"Fahad Al Abdulrazzaq": "فهد عبدالرزاق",
"Mohammed Mahzari": "محمد محزري",
"Ali Makki": "علي مكي",
"Hamad Al Yami": "حمد اليامي",
"Fahad Al Rashidi": "فهد الرشيدي",
"Abdulrahman Al Sanbi": "عبدالرحمن الصانبي",
"Nader Al Sharari": "نادر الشراري",
"Paulo Vítor": "باولو فيتور",
"Mohammed Al Saeed": "محمد السعيد",
"Abdulaziz Majrashi": "عبدالعزيز مجرشي",
"Muath Faqeehi": "معاذ فقيهي",
"Rakan Najjar": "راكان النجار",
"Victor Braga": "فيكتور براغا",
"Rakan Kaabi": "راكان كعبي",
"Dhari Al-Enezi": "ضاري العنزي",
"Roger Ibañez": "روجير إيبانيز",
"Nawaf Boushal": "نواف بوشل",
"Marzouq Tambakti": "مرزوق تمبكتي",
"Bono": "بونو",
"Majed Omar Kanabah": "ماجد عمر كنبة",
"Ahmad Al Harbi": "أحمد الحربي",
"Ahmed Bamasud": "أحمد با مسعود",
"Waleed Bakshween": "وليد باخشوين",
"Sultan Farhan": "سلطان فرحان",
"Ashraf El Mahdioui": "أشرف المهديوي",
"Sadio Mané": "ساديو ماني",
"Marwane Saadane": "مروان سعدان",
"Juan Pedroza": "خوان بيدروزا",
"Franck Kessié": "فرانك كيسي",
"Abdullah Al-Salem": "عبدالله السالم",
"Ziyad Aljohani": "زياد الجهني",
"Sergej Milinković-Savić": "سيرجي ميلينكوفيتش-سافيتش",
"Hassan Al Tambakti": "حسن تمبكتي",
"Mohammed Al-Khabrani": "محمد الخبراني",
"Fashion Sakala": "فاشيون ساكالا",
"Marcelo Brozović": "مارسيلو بروزوفيتش",
"Rayan Hamed": "ريان حامد",
"Ala'a Al-Hejji": "علاء الهجي",
"Naif Masoud": "نايف مسعود",
"Abdullah Al-Hamdan": "عبدالله الحمدان",
"Abdulrahman Al-Safri": "عبدالرحمن السفري",
"Saad Yaslam Balobaid": "سعد يسلم بالعبيد",
"Khaled Al-Semeiry": "خالد السميري",
"Saeed Al-Rabiei": "سعيد الربيعي",
"Mansour Al Bishi": "منصور البيشي",
"Abdulfattah Asiri": "عبدالفتاح عسيري",
"Saleh Al-Amri": "صالح العمري",
"Abdelkader Bedrane": "عبدالقادر بدران",
"Firas Al-Buraikan": "فراس البريكان",
"Thamer Al Khaibri": "ثامر الخيبري",
"Ali Hazazi": "علي هزازي",
"Mohanad Alqaydhi": "مهند القيضي",
"Mokher Al-Rashidi": "مخير الرشيدي",
"Mourad Batna": "مراد باتنا",
"Sofiane Bendebka": "سفيان بن دبكة",
"Osama Al Khalaf": "أسامة الخلف",
"Abdullah Al-Hafith": "عبدالله الحافظ",
"Georginio Wijnaldum": "جورجينيو فاينالدوم",
"Riyad Mahrez": "رياض محرز",
"Mukhtar Ali": "مختار علي",
"Salem Alnajdi": "سالم النجدي",
"Abdulbaset Hindi": "عبدالباسط هندي",
"Ali Al-Hassan": "علي الحسن",
"Tariq Mohammed": "طارق محمد",
"Radhi Al-Oteibi": "راطي العتيبي",
"Kalidou Koulibaly": "خاليدو كوليبالي",
"Nasser Al-Dawsari": "ناصر الدوسري",
"Ibrahim Al Zubaidi": "إبراهيم الزبيدي",
"Hamad Al-Jayzani": "حمد الجيزاني",
"Jack Hendry": "جاك هيندري",
"Khalid Al-Ghannam": "خالد الغنام",
"Bandar Al Mutairi": "بندر المطيري",
"Madallah Al-Olayan": "مد الله العليان",
"Sultan Al-Ghannam": "سلطان الغنام",
"Nawwaf Al Harthi": "نواف الحارثي",
"Ahmed Harisi": "أحمد حريصي",
"Abdulrahman Al Dosari": "عبدالرحمن الدوسري",
"Meshal Alaeli": "مشعل العلي",
"Hattan Bahebri": "هتان باهبري",
"Mubarak Al Rajeh": "مبارك الراجح",
"Salem Al-Dawsari": "سالم الدوسري",
"Karim Benzema": "كريم بنزيما",
"Alhwsawi Sanousi Mohammed": "Alhwsawi Sanousi محمد",
"Edouard Mendy": "إدوارد ميندي",
"Muhannad Shanqeeti": "مهند الشنقيطي",
"Ramzi Sawlan": "رمزي صولان",
"Waleed Al-Ahmed": "وليد الأحمد",
"Marwan Al-Haidari": "مروان الحيدري",
"Merih Demiral": "مريح ديميرال",
"Naif Assery": "نايف عسيري",
"Fahad Ayed Al-Rashidi": "فهد عايد الرشيدي",
"André Moreira": "أندريه موريرا",
"Zakaria Hawsawi": "زكريا هوساوي",
"Sultan Al Shehri": "سلطان الشهري",
"Yannick Carrasco": "يانييك كاراسكو",
"Ziyad Al-Sahafi": "زياد الصحفي",
"Abdullah Al-Hawsawi": "عبدالله هوساوي",
"Saud Salem": "سعود سالم",
"Bader Al Mutairi": "بدر المطيري",
"Moteb Al-Harbi": "متعب الحربي",
"Hazzaa Al-Ghamdi": "هزاع الغامدي",
"Saleh Al-Harthi": "صالح الحارثي",
"Khalid Alsubaie": "خالد السبيعي",
"N'Golo Kanté": "نغولو كونتي",
"Saleh Al-Shehri": "صالح الشهري",
"Hussain Qasim": "حسين قاسم",
"Rúben Neves": "روبن نيفيز",
"Abdulelah Al-Amri": "عبدالإله العمري",
"Yahia Al-Shehri": "يحيى الشهري",
"Mohammed Al Aqal": "محمد العقل",
"Abdulaziz Al-Aliwa": "عبدالعزيز العليوة",
"Abdulhadi Al-Harajin": "عبدالهادي الحراجين",
"Amir Saâyoud": "أمير سعيود",
"Ali Al Shaafi": "علي الشافي",
"Mohammed Al Fuhaid": "محمد الفهيد",
"Moussa Dembélé": "موسى ديمبيلي",
"Riyadh Sharahili": "رياض شراحيلي",
"Sultan Mandash": "سلطان مندش",
"Mohammed Yousef": "محمد يوسف",
"Hammam Al-Hammami": "همام الهمامي",
"Julián Quiñones": "خوليان كينيونيس",
"Arif Al-Haydar": "عارف الحيدر",
"Hamed Al-Ghamdi": "حامد الغامدي",
"Ali Al-Asmari": "علي الأسمري",
"Abderrazak Hamdallah": "عبدالرزاق حمدالله",
"Mohammed Al-Qahtani": "محمد القحطاني",
"Amin Al-Bukhari": "أمين البخاري",
"Abdulrahman Al-Obaid": "عبدالرحمن العبيد",
"Nahitan Nández": "ناهيتان نانديز",
"Ivan Toney": "إيفان توني",
"Awadh Khamis": "عوض خميس",
"Mansor Al Beshe": "منصور البيشي",
"Fahad Zubaidi": "فهد زبيدي",
"Hussain Al Zarie": "حسين الزارع",
"Bernard Mensah": "برنارد منساه",
"Ahmed Al-Ghamdi": "أحمد الغامدي",
"Abdulraoof Al-Deqeel": "عبدالرؤوف الدقيل",
"Abdulfattah Adam Mohammed": "عبدالفتاح آدم محمد",
"Tarek Hamed": "طارق حامد",
"Mohammed Al-Kuwaykibi": "محمد الكويكبي",
"Hamad Al Jayzani": "حمد الجيزاني",
"Faisal Al-Sibyani": "فيصل الصبياني",
"Awad Al-Nashri": "عوض الناشري",
"Nacho Fernández": "ناتشو فيرنانديز",
"Fawaz Al-Sagour": "فواز الصقور",
"Hazzaa Ahmed Al Ghamdi": "Hazzaa أحمد ال الغامدي",
"Radhi Al Otaibi": "Radhi ال العتيبي",
"Bassam Al-Hurayji": "بسام الحريجي",
"Ahmed Al-Kassar": "أحمد الكسار",
"Gastón Álvarez": "غاستون ألفاريز",
"Khaled Narey": "خالد ناري",
"Wesley Hoedt": "ويسلي هودت",
"Ali Albulayhi": "علي البليهي",
"Yasir Al-Shahrani": "ياسر الشهراني",
"Odion Ighalo": "أوديون إيغالو",
"Nawaf Al Saadi": "نواف السعدي",
"Mohammed Al-Absi": "محمد العبسي",
"Mohamed Kanno": "محمد كنو",
"Qassem Lajami": "قاسم لاجامي",
"Mohammed Abu Al-Shamat": "محمد أبو الشامات",
"Mohammed Alkhaibari": "محمد الخيبري",
"Sumaihan Al-Nabit": "سميحان النابت",
"Ahmed Al Julaydan": "أحمد الجليدان",
"Milan Borjan": "ميلان بورجان",
"Ayman Yahya": "أيمن يحيى",
"Saleh Al Qumayzi": "صالح القميزي",
"Mohammed Al-Mahasneh": "محمد المحاسنة",
"Khalifah Al-Dawsari": "خليفة الدوسري",
"Turki Al-Ammar": "تركي العمار",
"Noor Al-Rashidi": "نور الرشيدي",
"Marek Rodák": "ماريك روداك",
"Chris Smalling": "كريس سمولينغ",
"Mohammed Al-Fuhaid": "محمد Al-Fuhaid",
"Fahad Al-Reshedi": "فهد الرشيدي",
"Husain Al-Monassar": "حسين المنتشر",
"Majed Khalifah": "ماجد خليفة",
"Robert Renan": "روبيرت رينان",
"Abdulrahman Al Shammari": "عبدالرحمن الشمري",
"Moussa Diaby": "موسى ديابي",
"Jehad Thakri": "جهاد ذكري",
"Yoann Barbet": "يوان باربت",
"Abdullah Al-Qahtani": "عبدالله القحطاني",
"Mohammed Al-Fatil": "محمد الفتيل",
"Oumar Gonzalez": "أومار غونزاليس",
"Alex Collado": "أليكس كولادو",
"Aleksandar Mitrović": "ألكسندر ميتروفيتش",
"Hamdan Al-Shamrani": "حمدان الشمراني",
"Abdulrahman Alobud": "عبدالرحمن العبود",
"Jawad El Yamiq": "جواد الياميق",
"Naif Hazzazi": "نايف هزازي",
"Ali Mukhtar": "علي مختار",
"Raghid Najjar": "راغد النجار",
"Qasim Lajami": "قاسم لاجامي",
"Orlando Mosquera": "أورلاندو موسكيرا",
"Saad Al-Shurafa": "سعد الشرفاء",
"Karl Toko Ekambi": "كارل توكو إيكامبي",
"Fahad Bin Jumayah": "فهد بن جميعة",
"Saviour Godwin": "سافيور جودوين",
"Georges-Kévin N'Koudou": "جورج-كيفين نكودو",
"Fayçal Fajr": "فيصل فجر",
"Habib Diallo": "حبيب ديالو",
"Ibrahim Mahnashi": "إبراهيم محنشي",
"Mohammed Mazyad Alshammari": "محمد مزيد الشمري",
"Nawaf Al Sadi": "نواف ال Sadi",
"Paulo Victor": "باولو فيكتور",
"Koen Casteels": "كون كاستيلس",
"Islam Ahmed Hawsawi": "Islam أحمد هوساوي",
"Abduleallah Hawsawi": "Abduleallah هوساوي",
"Sattam Al-Roqi": "سطام الروقي",
"Nawaf Al-Hawsawi": "نواف هوساوي",
"Norbert Gyömbér": "نوربرت غيومبير",
"Mohammed Khalil Marran": "محمد خليل مران",
"Awdh Faraj": "عوض فرج",
"François Kamano": "فرانسوا كامانو",
"Mohammed Al Khabrani": "محمد ال Khabrani",
"Ghassan Hawsawi": "غسان هوساوي",
"Fahad Al Hamad": "فهد الحمد",
"Muteb Al-Mufarrij": "متعب المفرج",
"Mohamed Simakan": "محمد سيماكان",
"Abdullah Al-Khaibari": "عبدالله الخيبري",
"Mohammed Naji": "محمد ناجي",
"Mohammed Qassem": "محمد قاسم",
"Abdullah Al-Fahad": "عبدالله الفهد",
"Othman Al-Othman": "عثمان العثمان",
"Farouk Chafaï": "فاروق شافعي",
"Nawaf Al-Habashi": "نواف الحبشي",
"Christian Bassogog": "كريستيان باسوغوغ",
"Hussain Ahmed Al Issa": "حسين أحمد عيسى",
"Houssem Aouar": "حسام عوار",
"Mohamed Al Oqil": "محمد العقل",
"Mohammed Essa Harbush": "محمد Essa Harbush",
"Ibrahim Zaied": "إبراهيم زايد",
"Nawaf Al-Aqidi": "نواف العقيدي",
"Abdullah Al-Shanqiti": "عبدالله الشنقيطي",
"Kostas Fortounis": "كوستاس فورتونيس",
"Abdulaziz Al-Bishi": "عبدالعزيز البيشي",
"Raed Ozaybi": "رائد أزايبي",
"Bandar Nasser": "بندر ناصر",
"Abdullah Hazazi": "عبدالله هزازي",
"Majed Abdullah": "ماجد عبدالله",
"Predrag Rajković": "بريدراغ رايكوفيتش",
"Mohammed Al-Dosari": "محمد الدوسري",
"Ali Al-Salem": "علي السالم",
"Mustafa Malaika": "مصطفى ملائكة",
"Abdullah Al Khateeb": "عبدالله الخطيب",
"Gojko Cimirot": "غويكو سيميروت",
"Nicolae Stanciu": "نيكولاي ستانشيو",
"Musa Barrow": "موسى بارو",
"Waled Al Enazi": "وليد العنزي",
"Basil Yousef Al-Sayyali": "باسل يوسف السيالي",
"Roger Martínez": "روجير مارتينيز",
"Mohammed Al-Thain": "محمد Al-Thain",
"Y. Bounou": "ي. بونو",
"João Cancelo": "جواو كانسيلو",
"Yazeed Al Bakr": "يزيد البكر",
"Abdurahman Al-Dakheel": "عبدالرحمن الدخيل",
"Saad Bguir": "سعد بقير",
"Mohammed Qasem": "محمد Qasem",
"Abdulrahman Al Harthi": "عبدالرحمن ال Harthi",
"Sanousi Al Hawsawi": "Sanousi ال هوساوي",
"Nasser Al Bishi": "ناصر ال Bishi",
"Ziyad Aljari": "زياد Aljari",
"Majed Mohammed": "ماجد محمد",
"Saad Al-Mousa": "سعد Al-Mousa",
"Abdullah Al Hawsawi": "عبدالله ال هوساوي",
"Mohammed Al Dowaish": "محمد ال Dowaish",
"Abdulelah Al-Malki": "عبدالإله Al-Malki",
"Noor Al Rashidi": "Noor ال Rashidi",
"Nawaf Al Ghulaimish": "نواف ال Ghulaimish",
"Moteb Al Harbi": "Moteb ال الحربي",
"Steven Bergwijn": "ستيفن بيرجوين",
"Ahmed Hegazy": "أحمد حجازي",
"Hussain Al-Showaish": "حسين Al-Showaish",
"Saleh Al Harthi": "صالح ال Harthi",
"Majed Qasheesh": "ماجد Qasheesh",
"Mohammed Al Majhad": "محمد ال Majhad",
"Marwan Al Haidari": "Marwan ال Haidari",
"Arif Al Haydar": "Arif ال Haydar",
"Abdulelah Alshamary": "عبدالإله Alshamary",
"Abdulmajeed Al-Sulaiheem": "عبدالمجيد الصليهم",
"Hussain Ali Alnwaiqi": "حسين علي Alnwaiqi",
"Ahmed Al Rashidi": "أحمد ال Rashidi",
"Abdullah Abdo": "عبدالله Abdo",
"Hussain Al Nowaiqi": "حسين ال Nowaiqi",
"Mohammed Al Kunaydiri": "محمد ال Kunaydiri",
"Abdullah Al-Anazi": "عبدالله Al-Anazi",
"H. Al Ghamdi": "H. ال الغامدي",
"Ammar Al Dohaim": "Ammar ال Dohaim",
"Abdulaziz Al Bishi": "عبدالعزيز ال Bishi",
"Nawaf Al Quamiri": "نواف ال Quamiri",
"Makhir Al Rashidi": "Makhir ال Rashidi",
"Mohammed Al-Burayk": "محمد Al-Burayk",
"Abdullah Al Mogren": "عبدالله ال Mogren",
"Khalid Al Ghannam": "خالد ال Ghannam",
"Hussain Alsebyani": "حسين Alsebyani",
"Mohammed Al-Konaideri": "محمد Al-Konaideri",
"Abdullah Almogren": "عبدالله Almogren",
"Farhah Ali Alshamrani": "Farhah علي Alshamrani",
"Yousef Al-Shammari": "يوسف Al-Shammari",
"Meshari Fahad Al-Nemer": "Meshari فهد Al-Nemer",
"Ibrahim Šehić": "إبراهيم Šehić",
"Othman Al Othman": "عثمان ال عثمان",
"Ahmed Sharahili": "أحمد Sharahili",
"Meshal Al Mutairi": "Meshal ال المطيري",
"Khalid Al Rammah": "خالد ال Rammah",
"Abdullah Al-Amar": "عبدالله Al-Amar",
"Abdullah Al Muaiouf": "عبدالله ال Muaiouf",
"Amaar Al Dohaim": "Amaar ال Dohaim",
"Nawaf Al Qamiri": "نواف ال Qamiri",
"Abdullah Al-Mayouf": "عبدالله Al-Mayouf",
"Amin Al Bukhari": "Amin ال Bukhari",
"Ahmed Al Kassar": "أحمد ال Kassar",
"Meshal Ali Khayrallah": "Meshal علي Khayrallah",
"Faisal Al-Ghamdi": "فيصل Al-Ghamdi",
"Abdulaziz Al-Othman": "عبدالعزيز Al-Othman",
"Khalid Al-Kaabi": "خالد Al-Kaabi",
"Mohammed Al Mahasnah": "محمد ال Mahasnah",
"Hussain Al Shuwaysh": "حسين ال Shuwaysh",
"Mohammed Fallatah": "محمد Fallatah",
"Mohammed Al Abdullah": "محمد ال عبدالله",
"Mohammed Abusabaan": "محمد Abusabaan",
"Abdulaziz Rahma": "عبدالعزيز Rahma",
"Abdulrahman Al Obaid": "عبدالرحمن ال Obaid",
"Faisal Al Subiani": "فيصل ال Subiani",
"Abdulelah": "عبدالإله",
"Saad Fahad Al Nasser": "سعد فهد ال ناصر",
"Abdulrhman Al Anzi": "Abdulrhman ال Anzi",
"Mohammed Al-Majhad": "محمد Al-Majhad",
"S. Al Hamsal": "S. ال Hamsal",
"A. Al Hassan": "A. ال حسن",
"Abdulelah Al Malki": "عبدالإله ال Malki",
"Mohammed Al-Owais": "محمد Al-Owais",
"Islam Hawsawi": "Islam هوساوي",
"Hassan Hashim Al Ali": "حسن Hashim ال علي",
"B. Al Sayyali": "B. ال Sayyali",
"A. Hawsawi": "A. هوساوي",
"O. Al Boardi": "O. ال Boardi",
"S. Al Ghannam": "S. ال Ghannam",
"Abdullah Al Qahtani": "عبدالله ال القحطاني",
"Abdulrahman Al Bouq": "عبدالرحمن ال Bouq",
"Omar Hawsawi": "عمر هوساوي",
"Mohammed Al Owais": "محمد ال Owais",
"Malek Al Abdulmonam": "Malek ال Abdulmonam",
"Mohammed Al-Qarni": "محمد Al-Qarni",
"M. Al Baqawi": "M. ال Baqawi",
"Hussain Al Sultan": "حسين ال سلطان",
"Suwailem Al Manhali": "Suwailem ال Manhali",
"João Félix": "جواو فيليكس",
"Muhannad Al Saad": "Muhannad ال سعد",
"Haitham Mohammed Asiri": "Haitham محمد عسيري",
"Y. Al Shahrani": "Y. ال Shahrani",
"Anas Al Zahrani": "Anas ال الزهراني",
"Mohammed Al Qarni": "محمد ال Qarni",
"Raed Al Ghamdi": "Raed ال الغامدي",
"Ala Al Hajji": "Ala ال Hajji",
"Ammar Al Najjar": "Ammar ال Najjar",
"Sultan Tanker": "سلطان Tanker",
"Hassan Al-Asmari": "حسن Al-Asmari",
"Abdurahman Al Shammari": "Abdurahman ال الشمري",
"Waleed Bakshwn": "وليد Bakshwn",
"Rakan Al-Tulayhi": "راكان Al-Tulayhi",
"Hamad Al Abdan": "حمد ال Abdan",
"Jamaan Al Dawsari": "Jamaan ال الدوسري",
"Omar Al-Somah": "عمر Al-Somah",
"M. Al Thani": "M. ال Thani",
"R. Al Najjar": "R. ال Najjar",
"Ali Al Hussain": "علي ال حسين",
"Hassan Tambakti": "حسن Tambakti",
"Faris Al Ghamdi": "Faris ال الغامدي",
"Z. Al Johani": "Z. ال Johani",
"A. Al Asmari": "A. ال Asmari",
"Abdulrahman Al Anazi": "عبدالرحمن ال Anazi",
"Mohammed Al Absi": "محمد ال Absi",
"Nawaf Al Hawsawi": "نواف ال هوساوي",
"Waleed Al Anzi": "وليد ال Anzi",
"Mohammed Al-Yami": "محمد Al-Yami",
"Ibrahim Alnakhli": "إبراهيم Alnakhli",
"Khalid Bin Shuwayyi": "خالد بن Shuwayyi",
"A. Al Nashri": "A. ال Nashri",
"A. R. Al Khaibre": "A. R. ال Khaibre",
"I. Hawsawi": "I. هوساوي",
"M. Al Beshe": "M. ال Beshe",
"M. Brozovic": "م. بروزوفيتش",
"Awad Al Nashri": "Awad ال Nashri",
"Mohammed Al Oufi": "محمد ال Oufi",
"Saud Al Rashed": "Saud ال Rashed",
"Mohammed Al-Thani": "محمد Al-Thani",
"Mohammed Ali Barnawi": "محمد علي Barnawi",
"Khalifah Al Dawsari": "Khalifah ال الدوسري",
"Ali Abdullah Hazzazi": "علي عبدالله Hazzazi",
"Ahmed Mostafa": "أحمد Mostafa",
"Saleh Aboulshamat": "صالح Aboulshamat",
"S. Al Rashid": "S. ال Rashid",
"A. Al Obaid": "A. ال Obaid",
"R. Al Otaibi": "R. ال العتيبي",
"Suhayb Al Zaid": "Suhayb ال Zaid",
"Haitham Asiri": "Haitham عسيري",
"Ali Al Masoud": "علي ال Masoud",
"Abdulaziz Al-Harbi": "عبدالعزيز Al-Harbi",
"Nasser Al Haleel": "ناصر ال Haleel",
"Mohammed Al-Rubaie": "محمد Al-Rubaie",
"K. Al Samiri": "K. ال Samiri",
"Y. Al Shehri": "Y. ال Shehri",
"N. Al Harthi": "N. ال Harthi",
"Nawaf Al Aqidi": "نواف ال Aqidi",
"Mohammed Al Khaibari": "محمد ال Khaibari",
"Ahmed Al-Nakhli": "أحمد Al-Nakhli",
"Mohamed Al Makahasi": "Mohamed ال Makahasi",
"Nader Abdullah Al Sharari": "Nader عبدالله ال Sharari",
"Ali Alzubaidi": "علي Alzubaidi",
"A. Asiri": "A. عسيري",
"M. Al Khabrani": "M. ال Khabrani",
"A. Al Harabi": "A. ال Harabi",
"A. Al Hawsawi": "A. ال هوساوي",
"Mohammed Essa Hurbush": "محمد Essa Hurbush",
"Abdul Rahman Al Khaibari": "Abdul Rahman ال Khaibari",
"Mohammed Al Dossari": "محمد ال Dossari",
"Saleh Abu Al-Shamat": "صالح Abu Al-Shamat",
"A. Al Sanbi": "A. ال Sanbi",
"M. Abdulrahman": "M. عبدالرحمن",
"Z. Al Jari": "Z. ال Jari",
"M. Al Alaeli": "M. ال Alaeli",
"H. Al Yami": "H. ال Yami",
"Abdulmalik Al Harbi": "عبدالملك ال الحربي",
"Saleh Al Ohaymid": "صالح ال Ohaymid",
"Saleh Alohaymid": "صالح Alohaymid",
"H. Al Dubais": "H. ال Dubais",
"M. Al Shammari": "M. ال الشمري",
"A. Al Saluli": "A. ال Saluli",
"A. Al Harbi": "A. ال الحربي",
"A. Al Harfi": "A. ال Harfi",
"M. Al Qaydhi": "M. ال Qaydhi",
"Abdulelah Al Shammry": "عبدالإله ال Shammry",
"Abdullah Al Shanqiti": "عبدالله ال Shanqiti",
"Hassan Rubayyi": "حسن Rubayyi",
"Mohammed Abo Abd": "محمد Abo Abd",
"Abdullah Hussein Al-Owisher": "عبدالله حسين Al-Owisher",
"Abdulaziz Al-Shahrani": "عبدالعزيز Al-Shahrani",
"Abdullah Bukhari": "عبدالله Bukhari",
"Abdullah Alkhaibari": "عبدالله Alkhaibari",
"A. Al Julaydan": "A. ال Julaydan",
"Z. Al Sahafi": "Z. ال Sahafi",
"N. Al Dawsari": "N. ال الدوسري",
"Naser Al Ghamdi": "Naser ال الغامدي",
"Noah Al Mousa": "Noah ال Mousa",
"Ali Al Zubaidi": "علي ال Zubaidi",
"Moataz Al Baqawi": "Moataz ال Baqawi",
"Saeed Al Rubaie": "سعيد ال Rubaie",
"Ahmed Al-Shamrani": "أحمد Al-Shamrani",
"Ibrahim Al-Zubaidi": "إبراهيم Al-Zubaidi",
"Aloyayari Abdulmalik": "Aloyayari عبدالملك",
"Nawaf Alsadi": "نواف Alsadi",
"T. Abdullah": "T. عبدالله",
"M. Al Mufarrij": "M. ال Mufarrij",
"H. Al Zabdani": "H. ال Zabdani",
"B. Nasser": "B. ناصر",
"E. Al Muwallad": "E. ال Muwallad",
"A. Al Hafith": "A. ال Hafith",
"Mohammed Al Shammari": "محمد ال الشمري",
"Sattam Al Ruqi": "Sattam ال Ruqi",
"Saad Al Qahtani": "سعد ال القحطاني",
"Younes Al Shanqeeti": "Younes ال Shanqeeti",
"Abdullah Al Ghamdi": "عبدالله ال الغامدي",
"Ibrahim Zaid": "إبراهيم Zaid",
"Azzam Al Salman": "Azzam ال Salman",
"Waleed Abdullah": "وليد عبدالله",
"Salem Al Toiawy": "Salem ال Toiawy",
"Ammar Al Harfi": "Ammar ال Harfi",
"Rayan Enad": "ريان Enad",
"Fahad Al-Muwallad": "فهد Al-Muwallad",
"M. Al Jahif": "M. ال Jahif",
"M. Al Rubaie": "M. ال Rubaie",
"A. Al Shammeri": "A. ال Shammeri",
"Ahmed Al-Julaydan": "أحمد Al-Julaydan",
"Saad Al Salouli": "سعد ال Salouli",
"Basil Al Sayyali": "Basil ال Sayyali",
"Sharaf Al Salim": "Sharaf ال Salim",
"Mohammed Al-Sahihi": "محمد Al-Sahihi",
"Ali Al-Zaqan": "علي Al-Zaqan",
"Ahmad Zain": "أحمد Zain",
"K. A. Al Sibyani H.": "K. A. ال Sibyani H.",
"A. Al Safari": "A. ال Safari",
"A. Al Bukhari": "A. ال Bukhari",
"M. Al Sahihi": "M. ال Sahihi",
"N. Al Saadi": "N. ال Saadi",
"M. Al Absi": "M. ال Absi",
"Z. Al Ghamdi": "Z. ال الغامدي",
"A. Al Shammari": "A. ال الشمري",
"N. Al Hawsawi": "N. ال هوساوي",
"A. Al Swealem": "A. ال Swealem",
"H. Al Ali": "H. ال علي",
"Malek Al Abadalmanam": "Malek ال Abadalmanam",
"Mohammed Al Aqeel": "محمد ال Aqeel",
"Sattam Al Tumbukti": "Sattam ال Tumbukti",
"Majed Al Ghamdi": "ماجد ال الغامدي",
"Mohammed Al Ghamdi": "محمد ال الغامدي",
"Talal Al Absi": "Talal ال Absi",
"Hassan Al-Habib": "حسن Al-Habib",
"J. Al Dosari": "J. ال Dosari",
"S. Al Nasser": "S. ال ناصر",
"S. Al Najdi": "S. ال Najdi",
"M. Al Haidari": "M. ال Haidari",
"Mohammed Barnawi": "محمد Barnawi",
"Muhannad Al Shanqiti": "Muhannad ال Shanqiti",
"Mohammed Issa": "محمد Issa",
"Adeeb Al Haizan": "Adeeb ال Haizan",
"Abdulaziz Makin": "عبدالعزيز Makin",
"Saad Alselouli": "سعد Alselouli",
"F. Al Subiani": "F. ال Subiani",
"A. Al Awardi": "A. ال Awardi",
"F. Al Abdulraziq": "F. ال Abdulraziq",
"Hassan Al Asmari": "حسن ال Asmari",
"Bassam Al Hurayji": "Bassam ال Hurayji",
"Yousef Al Shammari": "يوسف ال الشمري",
"Mansour Al Shammari": "منصور ال الشمري",
"Abdulaziz Makeen": "عبدالعزيز Makeen",
"N. Al Sharari": "N. ال Sharari",
"F. Al Rashidi": "F. ال Rashidi",
"K. Al Shammari": "K. ال الشمري",
"S. Al Faraj": "S. ال Faraj",
"Jassim Al Ashban": "Jassim ال Ashban",
"Fahad Al Johani": "فهد ال Johani",
"Salman Al Faraj": "Salman ال Faraj",
"Abdulaziz Al-Dwehe": "عبدالعزيز Al-Dwehe",
"Jalal Al Salem": "Jalal ال Salem",
"A. Al Siyahi": "A. ال Siyahi",
"Hussain Al Eissa": "حسين ال Eissa",
"Rafi Al Ruwaili": "Rafi ال Ruwaili",
"Waleed Al Ahmad": "وليد ال أحمد",
"Moayad Al Houti": "Moayad ال Houti",
"Abdullah Al Shammari": "عبدالله ال الشمري",
"Mohammed Aldhulayfi": "محمد Aldhulayfi",
"Abdurahman Al Shammeri": "Abdurahman ال Shammeri",
"Abdullah Matuq": "عبدالله Matuq",
"Adib Al Haizan": "Adib ال Haizan",
"A. Al Kassar": "A. ال Kassar",
"N. Al Aqidi": "N. ال Aqidi",
"A. I. Al Khaibari": "A. I. ال Khaibari",
"A. Al Duqayl": "A. ال Duqayl",
"K. Al Rammah": "K. ال Rammah",
"A. Al Haydar": "A. ال Haydar",
"S. Al Sharfa": "S. ال Sharfa",
"K. Al Subaie": "K. ال Subaie",
"Mohammed Al Dosari": "محمد ال Dosari",
"Satam Al Lehiyani": "Satam ال Lehiyani",
"Madallah Al Olayan": "Madallah ال Olayan",
"Fahad Al-Johani": "فهد Al-Johani",
"A. Al Fawaz": "A. ال Fawaz",
"A. Al Khaibary": "A. ال Khaibary",
"Ziyad Al Jari": "زياد ال Jari",
"Salman Al Muwashar": "Salman ال Muwashar",
"Abdulrahman Al Rio": "عبدالرحمن ال Rio",
"Sultan Al Akouz": "سلطان ال Akouz",
"Abdulrahman Al-Khaibary": "عبدالرحمن Al-Khaibary",
"Abdullah Al-Jawaey": "عبدالله Al-Jawaey",
"Mohammed Al-Dawsari": "محمد Al-Dawsari",
"Ahmed Bandar Derwish": "أحمد بندر Derwish",
"Ahmed Abdoh Jaber": "أحمد Abdoh Jaber",
"Abdulrahman Khalid Al Rio": "عبدالرحمن خالد ال Rio",
"N. Al Ghamdi": "N. ال الغامدي",
"M. Al Baqaawi": "M. ال Baqaawi",
"Abdulaziz Al Awardi": "عبدالعزيز ال Awardi",
"Nawaf bin Saleh Al Azizi": "نواف بن صالح ال Azizi",
"Abdulaziz Al Fawaz": "عبدالعزيز ال Fawaz",
"Fahad Al Harbi": "فهد ال الحربي",
"Abdulrahman Al Dakheel": "عبدالرحمن ال Dakheel",
"Ayman Ahmed": "Ayman أحمد",
"K. Al Lazam": "K. ال Lazam",
"H. Al Jayzani": "H. ال Jayzani",
"T. Al Khaibri": "T. ال Khaibri",
"M. Al Sibyani": "M. ال Sibyani",
"Mohammed Baker": "محمد Baker",
"Ali Al Jubaya": "علي ال Jubaya",
"Abdulaziz Al-Swealem": "عبدالعزيز Al-Swealem",
"Ali Abdoulraouf Alabdrabalnabi": "علي Abdoulraouf Alabdrabalnabi",
"Fahd Mohammed Al-Harbi": "Fahd محمد Al-Harbi",
"W. Al Enezi": "W. ال العنزي",
"O. Al Othman": "O. ال عثمان",
"Abdul Rahman Al Ghamdi": "Abdul Rahman ال الغامدي",
"Rayan Al Mousa": "ريان ال Mousa",
"Rayan Albloushi": "ريان Albloushi",
"Ahmad Al Hbeab": "أحمد ال Hbeab",
"Abdullah Al Bishi": "عبدالله ال Bishi",
"A. Al Harajin": "A. ال Harajin",
"M. Al Aboud": "M. ال Aboud",
"S. Al Harthi": "S. ال Harthi",
"Rayan Al Bloushi": "ريان ال Bloushi",
"Sattam Al Shammari": "Sattam ال الشمري",
"Ahmed Shami": "أحمد Shami",
"Rakan Al Dosari": "راكان ال Dosari",
"Sultan Alessa": "سلطان Alessa",
"Feras Al Ghamdi": "Feras ال الغامدي",
"Khalid Al Asiri": "خالد ال عسيري",
"Abdullah Al Dossari": "عبدالله ال Dossari",
"Hussain Al-Sebyani": "حسين Al-Sebyani",
"Sultan Harun": "سلطان Harun",
"Omar Shami": "عمر Shami",
"Nawaf Al-Azizi": "نواف Al-Azizi",
"Rakan Al-Dosari": "راكان Al-Dosari",
"Omar Al-Ruwaili": "عمر Al-Ruwaili",
"Abdullah Al-Dossari": "عبدالله Al-Dossari",
"Khalid Al-Asiri": "خالد Al-Asiri",
"H. Asiri": "H. عسيري",
"H. Al Asmari": "H. ال Asmari",
"M. Abdullah": "M. عبدالله",
"Jawad Al Hassan": "Jawad ال حسن",
"Nawaf Al Abid": "نواف ال Abid",
"Abdullah Majrashi": "عبدالله Majrashi",
"Mukhir Al Rashidi": "Mukhir ال Rashidi",
"Mohammed Alsubaie": "محمد Alsubaie",
"Ahmed Al Siyahi": "أحمد ال Siyahi",
"Mohammed Petros": "محمد Petros",
"Nawaf Al-Abed": "نواف Al-Abed",
"Abdullah Magrshi": "عبدالله Magrshi",
"Bin Mahmoud": "بن Mahmoud",
"K. Al Muqaitib": "K. ال Muqaitib",
"M. Al Yahya": "M. ال Yahya",
"Saad Haqawi": "سعد Haqawi",
"Mohammed Al Saiari": "محمد ال Saiari",
"Saad Al-Nasser": "سعد Al-Nasser",
"Jaber Nasser Asiri": "Jaber ناصر عسيري",
"Fawaz Al Qarni": "Fawaz ال Qarni",
"Saad Natiq": "سعد Natiq",
"Khalid Al Muqiatyb": "خالد ال Muqiatyb",
"Mahdi Al Obod": "Mahdi ال Obod",
"Mohammed Al-Saiari": "محمد Al-Saiari",
"Mohammed Adams": "محمد Adams",
"Yousef Hussain Haqawi": "يوسف حسين Haqawi",
"Mohammed Said Al-Qahtani": "محمد Said Al-Qahtani",
"Hassan Al-Amri": "حسن Al-Amri",
"S. Al Essa": "S. ال Essa",
"S. Al Anzi": "S. ال Anzi",
"M. Al Sarnoukh": "M. ال Sarnoukh",
"Zaid Al Enezi": "Zaid ال العنزي",
"Khaled Al Rammah": "Khaled ال Rammah",
"Abdullah Tarmin": "عبدالله Tarmin",
"Rayan Al Dossary": "ريان ال Dossary",
"Yousef Haqawi": "يوسف Haqawi",
"Hassan Al Amri": "حسن ال Amri",
"Abdulmajeed Al Sulaiheem": "عبدالمجيد ال Sulaiheem",
"Ahmad Jamal": "أحمد Jamal",
"Ahmed Hassan": "أحمد حسن",
"Ali Al Azaizah": "علي ال Azaizah",
"Ahmed Al-Juwaid": "أحمد Al-Juwaid",
"H. Al Qahtani": "H. ال القحطاني",
"N. Al Bishi": "N. ال Bishi",
"Meshari Al Oufi": "Meshari ال Oufi",
"Turki Al Ghamil": "تركي ال Ghamil",
"Hassan Hashim Al-Ali": "حسن Hashim Al-Ali",
"Mohammed Al-Shanqiti": "محمد Al-Shanqiti",
"Turki Al Jaadi": "تركي ال Jaadi",
"Mutaz Bin Hibah": "Mutaz بن Hibah",
"Hassan Al Majhad": "حسن ال Majhad",
"Abdulrahman Al Yami": "عبدالرحمن ال Yami",
"Mohammed Al-Sarnoukh": "محمد Al-Sarnoukh",
"Hassan Al Mojhed": "حسن ال Mojhed",
"Ali Al-Boleahi": "علي Al-Boleahi",
"M. Al Ghamdi": "M. ال الغامدي",
"M. Al Rajeh": "M. ال Rajeh",
"M. Al Fatil": "M. ال Fatil",
"F. Al Hamad": "F. ال حمد",
"F. Al Saqour": "F. ال Saqour",
"M. Al Abdulmanam": "M. ال Abdulmanam",
"A. Al Jouei": "A. ال Jouei",
"Anas Al Ghamdi": "Anas ال الغامدي",
"Hassan Al Musallam": "حسن ال Musallam",
"Ibrahim Al Shuail": "إبراهيم ال Shuail",
"Riyadh Al Ibrahim": "Riyadh ال إبراهيم",
"Faisal Al-Sobhi": "فيصل Al-Sobhi",
"Mohammed Al Mahasneh": "محمد ال Mahasneh",
"Mohammed Majrashi": "محمد Majrashi",
"Khalid Al-Shammari": "خالد Al-Shammari",
"Sultan Al Anzi": "سلطان ال Anzi",
"Hassan Murtadh Al-Musallam": "حسن Murtadh Al-Musallam",
"Abdulkarim Al Sulaima": "Abdulkarim ال Sulaima",
"F. Al Mutairi": "F. ال المطيري",
"S. Al Mutairi": "S. ال المطيري",
"J. Al Hassan": "J. ال حسن",
"A. Al Najjar": "A. ال Najjar",
"Faisal Nahet": "فيصل Nahet",
"Mohammed Al Shanqiti": "محمد ال Shanqiti",
"Mohammed Al Rubaie": "محمد ال Rubaie",
"Yasir Shammari": "Yasir الشمري",
"Mansour Camara": "منصور Camara",
"Farhan Al Azzmi": "Farhan ال Azzmi",
"Abdulkarim Sultan": "Abdulkarim سلطان",
"Ibrahim Ashi": "إبراهيم Ashi",
"Ali Al-Oujami": "علي Al-Oujami",
"H. Al Eisa": "H. ال Eisa",
"Ali Abdulraouf": "علي Abdulraouf",
"Saad Al Qarni": "سعد ال Qarni",
"Azzam Al Bishi": "Azzam ال Bishi",
"Osama Al Mermesh": "Osama ال Mermesh",
"Ahmad Abu Rasen": "أحمد Abu Rasen",
"Faisal Al Mutairi": "فيصل ال المطيري",
"Turki Al-Jaadi": "تركي Al-Jaadi",
"F. Al Sobhi": "F. ال Sobhi",
"S. Al Shammari": "S. ال الشمري",
"M. Al Salkhadi": "M. ال Salkhadi",
"A. Omar": "A. عمر",
"Mishal Saad": "Mishal سعد",
"Abdullah Al Rashidi": "عبدالله ال Rashidi",
"Ibrahim Al Shuayl": "إبراهيم ال Shuayl",
"Yousef Saad Al Harbi": "يوسف سعد ال الحربي",
"Sulaiman Asiri": "Sulaiman عسيري",
"Rayan Hamidou": "ريان Hamidou",
"Abdulrahman Al Anzi": "عبدالرحمن ال Anzi",
"Mohammed Mansour Mile": "محمد منصور Mile",
"Nawaf Al-Rashwodi": "نواف Al-Rashwodi",
"Yousef Alharbi": "يوسف Alharbi",
"Iyad Luay Ali Madani": "Iyad Luay علي Madani",
"Turki Al-Mutairi": "تركي Al-Mutairi",
"A. Al Malki": "A. ال Malki",
"F. Al Abdulwahed": "F. ال Abdulwahed",
"T. Al Shubili": "T. ال Shubili",
"Hamed Al Shanqiti": "Hamed ال Shanqiti",
"Azm Al Sayil": "Azm ال Sayil",
"Hassan Abu Shararah": "حسن Abu Shararah",
"Jamaan Al Dosari": "Jamaan ال Dosari",
"Mohammed Al Dhulayfi": "محمد ال Dhulayfi",
"Nawaf Al Rashwodi": "نواف ال Rashwodi",
"Fahad Al Obaid": "فهد ال Obaid",
"Abdullah Al Joui": "عبدالله ال Joui",
"Turki Fahad Al Mutairi": "تركي فهد ال المطيري",
"Farhan Al Aazmi": "Farhan ال Aazmi",
"Rakan Abdulrahman bin Jaman": "راكان عبدالرحمن بن Jaman",
"Saad Al Mutairy": "سعد ال Mutairy",
"Raed Al Shanqiti": "Raed ال Shanqiti",
"Ahmed Omar": "أحمد عمر",
"Hussain Al-Shuweish": "حسين Al-Shuweish",
"Abdulrahman Al-Shammeri": "عبدالرحمن Al-Shammeri",
"A. Al Yuhaybi": "A. ال Yuhaybi",
"S. M. Al Harthi": "S. M. ال Harthi",
"Y. Al Shanqeeti": "Y. ال Shanqeeti",
"R. Al Shanqiti": "R. ال Shanqiti",
"M. Al Saeed": "M. ال سعيد",
"N. Al Gulaymish": "N. ال Gulaymish",
"K. Al Asbahi": "K. ال Asbahi",
"S. Al Mousa": "S. ال Mousa",
"Mutni Fareed Al Timawi": "Mutni Fareed ال Timawi",
"Abdullah Al Rawdhan": "عبدالله ال Rawdhan",
"Saud Al Ruwaili": "Saud ال Ruwaili",
"Majed Al Qahtani": "ماجد ال القحطاني",
"Turki Ba Al-Jawsh": "تركي Ba Al-Jawsh",
"Hassan Al Shamrani": "حسن ال Shamrani",
"Saud Al Dosari": "Saud ال Dosari",
"Rayan Hattan": "ريان Hattan",
"Khalil Al Absi": "Khalil ال Absi",
"Suwailem Al Menhali": "Suwailem ال Menhali",
"Abdullah Khalifa": "عبدالله Khalifa",
"Abdulkarim Al Qahtani": "Abdulkarim ال القحطاني",
"Amar Hamed Al Yuhaybi": "Amar Hamed ال Yuhaybi",
"Khaled Ali Al Asbahi": "Khaled علي ال Asbahi",
"Hassan Abu Sharara": "حسن Abu Sharara",
"Ibrahim Al-Sheail": "إبراهيم Al-Sheail",
"Hassan Alshammrani": "حسن Alshammrani",
"N. Al Rashidi": "N. ال Rashidi",
"A. M. Yousef H.": "A. M. يوسف H.",
"Muhannad Al Yahya": "Muhannad ال Yahya",
"Abdulrahman Al-Ghamdi": "عبدالرحمن Al-Ghamdi",
"Nasser Al Omran": "ناصر ال Omran",
"Abdullah Al Dosari": "عبدالله ال Dosari",
"Rayan Al Johani": "ريان ال Johani",
"Hassan Al Mohammedsaleh": "حسن ال Mohammedsaleh",
"Abdullah Al Owayshir": "عبدالله ال Owayshir",
"Hussain Al Shai'an": "حسين ال Shai'an",
"Abdulrahman Alsenaid": "عبدالرحمن Alsenaid",
"Nasser Al-Omran": "ناصر Al-Omran",
"Ivan Rakitić": "إيفان راكيتيتش",
"Munir Mohamedi": "منير المحمدي",
"Mohammed Al-Qunaian": "محمد Al-Qunaian",
"Rayan Saud Al Johani": "ريان Saud ال Johani",
"Hassan Al-Mohammed": "حسن Al-Mohammed",
"Hussein Shaian": "حسين Shaian",
"M. Al Mahasneh": "M. ال Mahasneh",
"O. Al Mermesh": "O. ال Mermesh",
"S. Abdullah": "S. عبدالله",
"A. Al Zaynaldeen": "A. ال Zaynaldeen",
"A. Al Hussain": "A. ال حسين",
"S. Al Tumbukti": "S. ال Tumbukti",
"Talal Al Shubili": "Talal ال Shubili",
"Youssef Al Tahan": "Youssef ال Tahan",
"Adel Al Mutairi": "Adel ال المطيري",
"Meshal Al Dawood": "Meshal ال Dawood",
"Omar Al Oudah": "عمر ال Oudah",
"Mohammed Maran": "محمد Maran",
"Mohammed Al Qunaian": "محمد ال Qunaian",
"Hazaa Al Hazaa": "Hazaa ال Hazaa",
"Mohammed Al-Zaid": "محمد Al-Zaid",
"Salem Abdullah": "Salem عبدالله",
"Abdullah Alzaynaldeen": "عبدالله Alzaynaldeen",
"Turki Sheafan": "تركي Sheafan",
"Faisal Darisi": "فيصل Darisi",
"Abdulaziz Awadh Masnom": "عبدالعزيز Awadh Masnom",
"K. Al Qahtani": "K. ال القحطاني",
"A. Al Anzi": "A. ال Anzi",
"A. Al Khanani": "A. ال Khanani",
"H. Al Juhani": "H. ال Juhani",
"M. Al Buainain": "M. ال Buainain",
"Y. Al Zubaidi": "Y. ال Zubaidi",
"Abdulrahman Al Senaid": "عبدالرحمن ال Senaid",
"Turki Al Madani": "تركي ال Madani",
"Hamad Al-Khorayef": "حمد Al-Khorayef",
"Mohammed Al Hakim": "محمد ال Hakim",
"Mohammed Al-Khaibari": "محمد Al-Khaibari",
"Abdulrahman Al-Dosari": "عبدالرحمن Al-Dosari",
"Saad Al Saleh": "سعد ال صالح",
"Ayman Al Hussaini": "Ayman ال Hussaini",
"Habib Al Watyan": "Habib ال Watyan",
"Hussain Ali Alnowaiqi": "حسين علي Alnowaiqi",
"Hassan Al Slis": "حسن ال Slis",
"Mohammed Hamad Alqahtani": "محمد حمد Alqahtani",
"Ahmed Al-Anzi": "أحمد Al-Anzi",
"Hassan Altambakti": "حسن Altambakti",
"Abdulaziz Al-Khanani": "عبدالعزيز Al-Khanani",
"Mohammed Eissa Al-Yami": "محمد Eissa Al-Yami",
"Saad Alsaleh": "سعد Alsaleh",
"Hassan Al Salis": "حسن ال Salis",
"M. Al Dawood": "M. ال Dawood",
"H. Al Musallam": "H. ال Musallam",
"M. Al Hakim": "M. ال Hakim",
"U. Hussein": "U. حسين",
"Tamim Al Shuqayran": "Tamim ال Shuqayran",
"Abdulaziz Masnom": "عبدالعزيز Masnom",
"Adnan Al Bishri": "Adnan ال Bishri",
"Sultan Al Harbi": "سلطان ال الحربي",
"Ridha Abdullah Ambadu": "Ridha عبدالله Ambadu",
"Abdulmajeed Al Khathami": "عبدالمجيد ال Khathami",
"Hussain Al Nattar": "حسين ال Nattar",
"Redha Al Abdullah": "Redha ال عبدالله",
"Bandar Ali": "بندر علي",
"Hassan Idris": "حسن Idris",
"Hassan Al Qayed": "حسن ال Qayed",
"Neymar": "نيمار",
"Abdullah Otayf": "عبدالله Otayf",
"Mohammed Alburayk": "محمد Alburayk",
"Yahya Al Shehri": "Yahya ال Shehri",
"Ahmed Majrashi": "أحمد Majrashi",
"Mohammed Sulaiman Bakor": "محمد Sulaiman Bakor",
"Ali Al-Bulaihi": "علي Al-Bulaihi",
"Mohammed Alghanem": "محمد Alghanem",
"Abdullah Jaman": "عبدالله Jaman",
"Abdulaziz Alswealem": "عبدالعزيز Alswealem",
"Hussain Alnattar": "حسين Alnattar",
"Omar Al-Aowda": "عمر Al-Aowda",
"Hassan Al Qaid": "حسن ال Qaid",
"Al Burayh Mahmoud": "ال Burayh Mahmoud",
"M. Al Ghanem": "M. ال Ghanem",
"M. Al Otaibi": "M. ال العتيبي",
"M. Al Kunaydiri": "M. ال Kunaydiri",
"Abdulaziz Hadhood": "عبدالعزيز Hadhood",
"Saad Al Muthary": "سعد ال Muthary",
"Mohammed Al Kadi": "محمد ال Kadi",
"Abdulrahman Sahhari": "عبدالرحمن Sahhari",
"Yaseen Khalid": "Yaseen خالد",
"Ali Al Jassem": "علي ال Jassem",
"Fahad Al-Rashidi": "فهد Al-Rashidi",
"Abdulrahman Al-Otaibi": "عبدالرحمن Al-Otaibi",
"Abdulaziz Al Harbi": "عبدالعزيز ال الحربي",
"Nasser Al Hadhood": "ناصر ال Hadhood",
"Abdullah Al Anazi": "عبدالله ال Anazi",
"Bader Nawaf": "بدر نواف",
"Sultan Al Farhan": "سلطان ال Farhan",
"Majed Mohammed Sharrahi": "ماجد محمد Sharrahi",
"Rayan Al-Ghamdi": "ريان Al-Ghamdi",
"Mohammed Al-Otaibi": "محمد Al-Otaibi",
"Mohammed Alkadi": "محمد Alkadi",
"Nasser Hadhood": "ناصر Hadhood",
"Abdullah Safuq Al-Enezi": "عبدالله Safuq Al-Enezi",
"Bader Al Anazi": "بدر ال Anazi",
"Waheb Saleh": "Waheb صالح",
"S. Al Jadany": "S. ال Jadany",
"S. Al Roqi": "S. ال Roqi",
"T. Al Shaifan": "T. ال Shaifan",
"A. Al Marwani": "A. ال Marwani",
"R. Al Attar": "R. ال Attar",
"Abdulrahman Sayadi": "عبدالرحمن Sayadi",
"Thamer Al Dhafeeri": "Thamer ال Dhafeeri",
"Turki Ba Al Jawsh": "تركي Ba ال Jawsh",
"Turki Al Shaifan": "تركي ال Shaifan",
"Saud Al Tumbukti": "Saud ال Tumbukti",
"Mohammed Hazazi": "محمد Hazazi",
"Ahmed Kaabi": "أحمد Kaabi",
"Khalid Hazazi": "خالد Hazazi",
"Thamer Al Ali": "Thamer ال علي",
"Abdulilah Al Ghamdi": "Abdulilah ال الغامدي",
"Feras Al Rajhi": "Feras ال Rajhi",
"Omar Al Sharari": "عمر ال Sharari",
"Osama Al Turki": "Osama ال تركي",
"Mohammed Al Saedi": "محمد ال Saedi",
"Abdullah Al Ajyan": "عبدالله ال Ajyan",
"Abdullah Al Jadani": "عبدالله ال Jadani",
"Saud Zaid Al Bawardi": "Saud Zaid ال Bawardi",
"Hazza Al Hazza": "Hazza ال Hazza",
"Sattam Al Subaiei": "Sattam ال Subaiei",
"Abdulrahman Al Alawi": "عبدالرحمن ال Alawi",
"Saleh Abu Al Shamat": "صالح Abu ال Shamat",
"Ziyad Al Refaei": "زياد ال Refaei",
"Salman Al Mowasher": "Salman ال Mowasher",
"Rakan Al Tulayhi": "راكان ال Tulayhi",
"Saad Al Muwallad": "سعد ال Muwallad",
"Yousef Al Aqil": "يوسف ال Aqil",
"Abdullah Saad Al Shaflut": "عبدالله سعد ال Shaflut",
"Omar Al Soma": "عمر ال Soma",
"Nawaf Al-Harthi": "نواف Al-Harthi",
"Hamed Abdullah Yousef": "Hamed عبدالله يوسف",
"Rakan Al Kabi": "راكان ال Kabi",
"Abdullah Masoud": "عبدالله Masoud",
"Mohammed Yahya Hazazi": "محمد Yahya Hazazi",
"Ali Salah Aljassem": "علي Salah Aljassem",
"Rayan Fourig": "ريان Fourig",
"Abdullah Al-Jadani": "عبدالله Al-Jadani",
"Rakan Rajeh Altulayhi": "راكان Rajeh Altulayhi",
"Saad Almuwalad": "سعد Almuwalad",
"M. Al Shahrani": "M. ال Shahrani",
"S. Al Zaid": "S. ال Zaid",
"A. Al Otaibi": "A. ال العتيبي",
"A. Al Zaid": "A. ال Zaid",
"N. Abdulrahman": "N. عبدالرحمن",
"N. Al Bashri": "N. ال Bashri",
"N. Al Sadi": "N. ال Sadi",
"Y. Al Jaber": "Y. ال Jaber",
"Saleh Al Saeed": "صالح ال سعيد",
"Jumaan Al Dosari": "Jumaan ال Dosari",
"Nawaf Mazen Al Hawairy": "نواف Mazen ال Hawairy",
"Sultan Al Essa": "سلطان ال Essa",
"Bandar Al Shamrani": "بندر ال Shamrani",
"Zaid Al Bawardi": "Zaid ال Bawardi",
"Mohammed Al Yami": "محمد ال Yami",
"Meshal Al Shahrani": "Meshal ال Shahrani",
"Abdulrahman Nabza": "عبدالرحمن Nabza",
"Nawaf Al-Bishri": "نواف Al-Bishri",
"Abdulsalam Ali Barnawi": "Abdulsalam علي Barnawi",
"Saleh Al-Saeed": "صالح Al-Saeed",
"Abdullah Saeed": "عبدالله سعيد",
"Abdulaziz Making": "عبدالعزيز Making",
"Mohammed Al Dawsari": "محمد ال الدوسري",
"Abdullah Hussein Al Owisher": "عبدالله حسين ال Owisher",
"S. Al Johani": "S. ال Johani",
"N. Al Daajani": "N. ال Daajani",
"Y. Al Ruwaili": "Y. ال Ruwaili",
"A. Al Faraj": "A. ال Faraj",
"M. Al Nemer": "M. ال Nemer",
"A. Al Ajian": "A. ال Ajian",
"R. Al Mutairi": "R. ال المطيري",
"T. Al Madani": "T. ال Madani",
"R. Al Ghamdi": "R. ال الغامدي",
"M. Al Saedi": "M. ال Saedi",
"A. Al Senaid": "A. ال Senaid",
"I. Al Shuayl": "I. ال Shuayl",
"H. Al Wutaian": "H. ال Wutaian",
"N. Al Rashwodi": "N. ال Rashwodi",
"Ali Sharahili": "علي Sharahili",
"Abdulmalik Al Khaibari": "عبدالملك ال Khaibari",
"Mubarak Al Buainain": "Mubarak ال Buainain",
"Nawaf Al Jadaani": "نواف ال Jadaani",
"Ammar Al Hudaybi": "Ammar ال Hudaybi",
"Ahmed Al Daghrir": "أحمد ال Daghrir",
"Abdul Rahman Al Shammari": "Abdul Rahman ال الشمري",
"Faraj Al Rashid": "Faraj ال Rashid",
"Mohammed Al Sufyani": "محمد ال Sufyani",
"Abdullah Fallatah": "عبدالله Fallatah",
"Basil Hilwan Al Anzi": "Basil Hilwan ال Anzi",
"Ali Al-Essa": "علي Al-Essa",
"Fahad Al Jayzani": "فهد ال Jayzani",
"Hussain Al-Shurafa": "حسين Al-Shurafa",
"Hussain Al-Raqwani": "حسين Al-Raqwani",
"Yassine Bounou": "ياسين بونو",
"Murad Al Hawsawi": "Murad ال هوساوي",
"Khalid Al-Harbi": "خالد Al-Harbi",
"Abdulrahman Al-Shereaf": "عبدالرحمن Al-Shereaf",
"Mohammed Al-Hasawi": "محمد Al-Hasawi",
"Abdullah Bin Subayt": "عبدالله بن Subayt",
"Adeeb Al Hassan": "Adeeb ال حسن",
"Omar Mascarell": "عمر Mascarell",
"Rayan Al Sharekh": "ريان ال Sharekh",
"Mohammed Al Shaeri": "محمد ال Shaeri",
"Abdulaziz Al Murdih": "عبدالعزيز ال Murdih",
"Mohammed Al Qunayan": "محمد ال Qunayan",
"Abdulaziz Al Faraj": "عبدالعزيز ال Faraj",
"Sharafi Al Saleem": "Sharafi ال Saleem",
"Fahad Abdulrahman Hashim": "فهد عبدالرحمن Hashim",
"Waseem Al Shehri": "Waseem ال Shehri",
"Abdulraouf Al Dakheel": "Abdulraouf ال Dakheel",
"Farhan Al Azmi": "Farhan ال Azmi",
"Malek Al Abdulmanam": "Malek ال Abdulmanam",
"Abduallah Al Dossary": "Abduallah ال Dossary",
"Abdul Rahman Al Hajri": "Abdul Rahman ال Hajri",
"Faisal Abdulrazaq": "فيصل Abdulrazaq",
"Fahad Al Munaif": "فهد ال Munaif",
"Hussein Freij": "حسين Freij",
"Yazan Abdullah Al-Ruwaili": "Yazan عبدالله Al-Ruwaili",
"Fares Bandar Al Zahrani": "Fares بندر ال الزهراني",
"Fares Ahmed Al Ghafli": "Fares أحمد ال Ghafli",
"Rashid Al Mutairi": "Rashid ال المطيري",
"Marcelo Brozovic": "مارسيلو بروزوفيتش",
"Sadio Mane": "ساديو ماني",
"Rakan Al-Ghamdi": "راكان Al-Ghamdi",
"Ahmed Khatir": "أحمد Khatir",
"Majed Madani": "ماجد Madani",
"Nasser Al-Sadi": "ناصر Al-Sadi",
"Muntathir Al Shaqaq": "Muntathir ال Shaqaq",
"Ahmed Aldaghrir": "أحمد Aldaghrir",
"Rayan Al-Sharekh": "ريان Al-Sharekh",
"Mohammed Al-Shaeri": "محمد Al-Shaeri",
"Abdulaziz Almurdih": "عبدالعزيز Almurdih",
"Abdulaziz Al-Faraj": "عبدالعزيز Al-Faraj",
"Aiman Ahmed": "Aiman أحمد",
"Hawsawi Islam Ahmed": "هوساوي Islam أحمد",
"Fahad Muneef": "فهد Muneef",
"A. Al Bouq": "A. ال Bouq",
"A. Al Fahad": "A. ال فهد",
"B. Al Mutairi": "B. ال المطيري",
"F. Al Azzmi": "F. ال Azzmi",
"A. Al Hujaili": "A. ال Hujaili",
"W. Al Shanqiti": "W. ال Shanqiti",
"M. Al Hamdani": "M. ال Hamdani",
"M. Al Mutairi": "M. ال المطيري",
"W. Abdullah": "W. عبدالله",
"K. Al Asiri": "K. ال عسيري",
"A. Al Hadhood": "A. ال Hadhood",
"Y. Al Dosari": "Y. ال Dosari",
"H. Al Khorayef": "H. ال Khorayef",
"F. Al Zahrani": "F. ال الزهراني",
"A. Al Youssef": "A. ال Youssef",
"B. Al Dawaa": "B. ال Dawaa",
"B. Al Qahtani": "B. ال القحطاني",
"A. Abdulaziz Al Jwayzan": "A. عبدالعزيز ال Jwayzan",
"Y. Al honaifesh": "Y. ال honaifesh",
"K. Al Karani": "K. ال Karani",
"N. Al Hawairy": "N. ال Hawairy",
"A. Al Jaber": "A. ال Jaber",
"D. Al Habeeb": "D. ال Habeeb",
"A. Al Muhaysin": "A. ال Muhaysin",
"R. Al Dossary": "R. ال Dossary",
"M. Al Nuqaydan": "M. ال Nuqaydan",
"M. Al Shqaq": "M. ال Shqaq",
"S. Al Qarni": "S. ال Qarni",
"R. Al Bloushi": "R. ال Bloushi",
"A. Al Shaafi": "A. ال Shaafi",
"M. Al Abdullah": "M. ال عبدالله",
"F. Al Jumaiya": "F. ال Jumaiya",
"A. Al Ruhaili": "A. ال Ruhaili",
"J. Al Oshbaan": "J. ال Oshbaan",
"Mohammed Al Ghanem": "محمد ال Ghanem",
"Majed Alawad": "ماجد Alawad",
"Bandar Mofrh": "بندر Mofrh",
"Mohammed Al Nuqaydan": "محمد ال Nuqaydan",
"Ibrahim Al Hazmi": "إبراهيم ال Hazmi",
"Ali Al Sakakir": "علي ال Sakakir",
"Ibrahim Al Zahrani": "إبراهيم ال الزهراني",
"Ziyad Al Ghamdi": "زياد ال الغامدي",
"Mohammed Al Muhaysh": "محمد ال Muhaysh",
"Ibrahim Al Hamlan": "إبراهيم ال Hamlan",
"Mohammed Al Zubaidi": "محمد ال Zubaidi",
"Ahmed Darwish": "أحمد Darwish",
"Mubarak Al Shayie": "Mubarak ال Shayie",
"Mishal Al Ruwaili": "Mishal ال Ruwaili",
"Mehdi Al Aboud": "Mehdi ال Aboud",
"M. Al Dossary": "M. ال Dossary",
"M. Al Dowaish": "M. ال Dowaish",
"A. Al Harshan": "A. ال Harshan",
"Ahmed Asiri": "أحمد عسيري",
"Mansour Al Nakhli": "منصور ال Nakhli",
"Mohammed Al Hazmi": "محمد ال Hazmi",
"Waleed Hibah": "وليد Hibah",
"Mohammed Suhluli": "محمد Suhluli",
"Ahmad Abu Raseen": "أحمد Abu Raseen",
"Nawaf Al Bishri": "نواف ال Bishri",
"Hassan Rabea": "حسن Rabea",
"Ahmed Al Nakhli": "أحمد ال Nakhli",
"Mansour Jawhar": "منصور Jawhar",
"Nasser Al-Daajani": "ناصر Al-Daajani",
"Mohammed Al Hamdani": "محمد ال Hamdani",
"Yazeed Al-Dosari": "يزيد Al-Dosari",
"Turki Alammar": "تركي Alammar",
"Ahmed Gabal": "أحمد Gabal",
"Ali Al Youssef": "علي ال Youssef",
"Mohammed Bumuaykel": "محمد Bumuaykel",
"Abdulaziz Al Suwailem": "عبدالعزيز ال Suwailem",
"Hassan Ali Al Ghazal": "حسن علي ال Ghazal",
"Belal Mousa Ali Al Dawaa": "Belal Mousa علي ال Dawaa",
"Ruben Neves": "روبن نيفيز",
"Sergej Milinkovic-Savic": "سيرجي ميلينكوفيتش-سافيتش",
"Marek Rodak": "ماريك روداك",
"Moussa Dembele": "موسى ديمبيلي",
"Abdulah Al Jwayzan": "Abdulah ال Jwayzan",
"Abdulaziz Jurmush": "عبدالعزيز Jurmush",
"Yousef Al honaifesh": "يوسف ال honaifesh",
"Ahmed Namazi": "أحمد Namazi",
"Abdulmalik Al-Jaber": "عبدالملك Al-Jaber",
"Danyal Al Habeeb": "Danyal ال Habeeb",
"Ali Al Nakhli": "علي ال Nakhli",
"Sultan": "سلطان",
"Abdulelah Daghar": "عبدالإله Daghar",
"Bandar Essa Mofrh": "بندر Essa Mofrh",
"Majed Saleh Alawad": "ماجد صالح Alawad",
"Ali Alsakakir": "علي Alsakakir",
"Ibrahim Alhazmi": "إبراهيم Alhazmi",
"Mohammed Alnuqaydan": "محمد Alnuqaydan",
"Ibrahim Alzahrani": "إبراهيم Alzahrani",
"Mohammed Bin Muhaysh": "محمد بن Muhaysh",
"Faris Al Zubaidi": "Faris ال Zubaidi",
"Malik Al Shammary": "Malik ال Shammary",
"Mishaal Al Ruwaili": "Mishaal ال Ruwaili",
"Mohammed Dakhil Al-Dawsari": "محمد Dakhil Al-Dawsari",
"Ali Dhafer Al Harshan": "علي Dhafer ال Harshan",
"Fahad Majed Alhubayshi": "فهد ماجد Alhubayshi",
"Abdulilah Al Tale": "Abdulilah ال Tale",
"Ibrahim Al Abood": "إبراهيم ال Abood",
"Asiri": "عسيري",
"Mansour Alnakhli": "منصور Alnakhli",
"Mohammed Alhazmi": "محمد Alhazmi",
"Al Shamrani Bandar": "ال Shamrani بندر",
"Waleed Bin Hibah": "وليد بن Hibah",
"Nawaf Nasser Albishri": "نواف ناصر Albishri",
"Abdulaziz Al-Alawi": "عبدالعزيز Al-Alawi",
"A. Al Mogren": "A. ال Mogren",
"A. Al Shereaf": "A. ال Shereaf",
"S. Al Amri": "S. ال Amri",
"F. Al Shamrani": "F. ال Shamrani",
"S. Mane": "س. ماني"
}""")


def fold(s):
    """بصمة مرنة: تجريد اللكنات وتوحيد الشرطة والمسافة"""
    s = unicodedata.normalize("NFKD", (s or "").strip())
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = s.replace("'", "").replace("\u2019", "")
    s = re.sub(r"[-.]", " ", s)
    return " ".join(s.split()).lower()


rows = list(csv.DictReader(io.open("players_ar.csv", encoding="utf-8-sig")))
folded = {fold(k): v for k, v in FILL.items()}

n = skipped = 0
matched = set()
for r in rows:
    key = fold(r["player_en"])
    if key in folded:
        matched.add(key)
        if (r["player_ar"] or "").strip():
            skipped += 1
            continue
        r["player_ar"] = folded[key]
        n += 1

missing = [k for k in FILL if fold(k) not in matched]

with io.open("players_ar.csv", "w", encoding="utf-8-sig", newline="") as f:
    w = csv.DictWriter(f, fieldnames=["priority", "goals", "league",
                                      "team_ar", "player_en",
                                      "player_ar"])
    w.writeheader()
    w.writerows(rows)

d = [r for r in rows if r["priority"] == "D"]
done_d = sum(1 for r in d if (r["player_ar"] or "").strip())
total = sum(1 for r in rows if (r["player_ar"] or "").strip())

print(f"أُضيف: {n}  |  مترجَم أصلاً: {skipped}")
print(f"لم يُوجد بالملف: {len(missing)}")
if missing[:15]:
    for m in missing[:15]:
        print("   ", m)
    if len(missing) > 15:
        print(f"    ... و{len(missing)-15} غيرها")
print()
print(f"الفئة D: {done_d} من {len(d)}")
print(f"الإجمالي: {total} من {len(rows)}")
